# -*- coding: utf-8 -*-
"""Area and circumference of a circle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_HEqRovlJLGbRjQqhW7BNuQ3BJNW5S7
"""

#AREA & CIRCUMFERENCE OF A CIRCLE

import math

r = float(input("Enter the radius of the circle: "))

area = math.pi * r * r

circumference = 2 * math.pi * r

print(F"Area of the circle is {area}")
print(F"Circumference of the circle is {circumference}")